### ISSUE TITLE
Community question

### ISSUE THREAD

**Issue by tumb1er** [tumb1er/bamboo-build-tools#10]
I've recently merged second pull-request from unknown contributors. Initially, BBT was internal project for in-company usage. If anybody is interested in, I'll try to clean company-specific mess out and add more documentation.

Comments from unknown people are welcome :)

Sergey

**Comment by dirkmoors** [comment]
Hey @tumb1er, thank you for your contribution to the community! 
I'm evaluating the use of this library in my own CI processes, and it looks promising!
I would love to see this package appear (preferably as a python Wheel) on PyPi!
Cheers

**Comment by tumb1er** [comment]
Hi! Internally we use bbt-build and bbt-integrate scripts, and you? `svn-*` and `task-*` are console-oriented unix-style blocks for building integration workflow, and bbt-integrate is composite python all-in-one solution. Which is more interesting for you?

**Comment by dirkmoors** [comment]
Hi, for now, I use the 'coverage2clover' tool, since I only just started (actually mostly investigating) to migrate towards Bamboo. I use it in conjunction with 'tox'.

I'm currently using bamboo-build-tools from my own fork, but as soon as it's available via PyPi, I'll start using it from there.

```ini
[tox]
envlist =
    check,
    coverage,
    {py276,py342,pypy240}
skipsdist = True

[flake8]
max-line-length = 160
exclude = tests/*,*/migrations/*,*/south_migrations/*
ignore = F401,W391,E302,E241,E128,F403,E123

[testenv]
deps =
    -r{toxinidir}/requirements-production.txt
install_command = pip install --pre --upgrade {opts} {packages}
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}
passenv = *
commands =
    python manage.py test

[testenv:check]
deps =
    flake8>=2.4.1
usedevelop = true
commands =
    flake8 vikingid

[testenv:coverage]
deps =
    -r{toxinidir}/requirements-production.txt
    coverage>=4.0a6
    git+https://github.com/dirkmoors/bamboo-build-tools.git@master#egg=bamboo-build-tools
commands =
    coverage run --source='.' --omit=".tox/{envname}/*" manage.py test
    mkdir -p target/site/clover/
    coverage xml -o target/site/clover/coverage.xml
    coverage html -d target/site/clover/
    coverage2clover -i target/site/clover/coverage.xml -o target/site/clover/clover.xml

```

**Comment by tumb1er** [comment]
Well, recently have published coverage2clover as separate project to Pypi: https://github.com/tumb1er/coverage2clover

Hope will available in `pip search` soon.

Other bamboo tools are too specific for our company svn version management, so if nobody is interested in it, I'll leave it as-is.
